#!/usr/bin/env python3
"""Generate small graph correctness cases and compare DAWN outputs.

The suite intentionally uses tiny deterministic graphs so it can run on any
machine. It covers random, power-law-like, grid, path, star, directed,
undirected, weighted, and unweighted inputs.
"""

from __future__ import annotations

import argparse
import heapq
import math
import random
import shutil
import subprocess
from collections import deque
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple


Edge = Tuple[int, int, float]


class SkipAlgorithm(Exception):
    """Raised when a graph kind does not apply to an algorithm."""


def canonical_edges(edges: Iterable[Edge], directed: bool) -> List[Edge]:
    out: Dict[Tuple[int, int], float] = {}
    for u, v, w in edges:
        if u == v:
            continue
        a, b = (u, v) if directed or u < v else (v, u)
        key = (a, b)
        if key not in out or w < out[key]:
            out[key] = w
    return [(u, v, out[(u, v)]) for u, v in sorted(out)]


def adjacency(n: int, edges: Sequence[Edge], directed: bool) -> List[List[Tuple[int, float]]]:
    adj: List[List[Tuple[int, float]]] = [[] for _ in range(n)]
    for u, v, w in edges:
        adj[u].append((v, w))
        if not directed:
            adj[v].append((u, w))
    return adj


def write_mtx(path: Path, n: int, edges: Sequence[Edge], directed: bool, weighted: bool) -> None:
    field = "real" if weighted else "pattern"
    symmetry = "general" if directed else "symmetric"
    with path.open("w", encoding="utf-8") as f:
        f.write(f"%%MatrixMarket matrix coordinate {field} {symmetry}\n")
        f.write("% generated by validation/correctness/generate_and_check.py\n")
        f.write(f"{n} {n} {len(edges)}\n")
        for u, v, w in edges:
            if weighted:
                f.write(f"{u + 1} {v + 1} {w:.6f}\n")
            else:
                f.write(f"{u + 1} {v + 1}\n")


def write_sources(path: Path, sources: Sequence[int]) -> None:
    with path.open("w", encoding="utf-8") as f:
        for source in sources:
            f.write(f"{source}\n")


def parse_pairs(path: Path, value_type: str) -> Dict[Tuple[int, int], float]:
    result: Dict[Tuple[int, int], float] = {}
    if not path.exists():
        raise AssertionError(f"missing output file: {path}")
    for raw in path.read_text(encoding="utf-8").splitlines():
        if not raw.strip():
            continue
        parts = raw.split()
        if len(parts) == 3:
            u = int(parts[0])
            v = int(parts[1])
            val = float(parts[2])
            result[(u, v)] = int(val) if value_type == "int" else val
        elif len(parts) == 2:
            v = int(parts[0])
            val = float(parts[1])
            result[(-1, v)] = val
        else:
            raise AssertionError(f"malformed output line in {path}: {raw}")
    return result


def bfs_distances(adj: Sequence[Sequence[Tuple[int, float]]], source: int) -> List[int]:
    dist = [0] * len(adj)
    q: deque[int] = deque()
    for v, _ in adj[source]:
        dist[v] = 1
        q.append(v)
    while q:
        u = q.popleft()
        for v, _ in adj[u]:
            if dist[v] == 0 and v != source:
                dist[v] = dist[u] + 1
                q.append(v)
    return dist


def dijkstra(adj: Sequence[Sequence[Tuple[int, float]]], source: int) -> List[float]:
    inf = float("inf")
    dist = [inf] * len(adj)
    dist[source] = 0.0
    heap: List[Tuple[float, int]] = [(0.0, source)]
    while heap:
        d, u = heapq.heappop(heap)
        if d != dist[u]:
            continue
        for v, w in adj[u]:
            nd = d + w
            if nd < dist[v]:
                dist[v] = nd
                heapq.heappush(heap, (nd, v))
    return dist


def closeness_from_distances(dist: Sequence[float], n: int) -> float:
    total = sum(d for d in dist if math.isfinite(d))
    if total == 0:
        return 0.0
    return (n - 1) / total


def brandes_unweighted(adj: Sequence[Sequence[Tuple[int, float]]], directed: bool) -> List[float]:
    n = len(adj)
    bc = [0.0] * n
    for s in range(n):
        stack: List[int] = []
        pred: List[List[int]] = [[] for _ in range(n)]
        sigma = [0.0] * n
        dist = [-1] * n
        sigma[s] = 1.0
        dist[s] = 0
        q: deque[int] = deque([s])
        while q:
            v = q.popleft()
            stack.append(v)
            for w, _ in adj[v]:
                if dist[w] < 0:
                    dist[w] = dist[v] + 1
                    q.append(w)
                if dist[w] == dist[v] + 1:
                    sigma[w] += sigma[v]
                    pred[w].append(v)
        delta = [0.0] * n
        while stack:
            w = stack.pop()
            for v in pred[w]:
                if sigma[w] != 0:
                    delta[v] += (sigma[v] / sigma[w]) * (1.0 + delta[w])
            if w != s:
                bc[w] += delta[w]
    if not directed:
        bc = [x / 2.0 for x in bc]
    if n > 2:
        bc = [x / ((n - 1) * (n - 2)) for x in bc]
    return bc


def expected_bfs(adj: Sequence[Sequence[Tuple[int, float]]], source: int) -> Dict[Tuple[int, int], float]:
    dist = bfs_distances(adj, source)
    return {(source, v): d for v, d in enumerate(dist) if v != source and d > 0}


def expected_sssp(adj: Sequence[Sequence[Tuple[int, float]]], source: int) -> Dict[Tuple[int, int], float]:
    dist = dijkstra(adj, source)
    return {(source, v): d for v, d in enumerate(dist) if v != source and math.isfinite(d) and d != 0}


def expected_mssp_unweighted(
    adj: Sequence[Sequence[Tuple[int, float]]], sources: Sequence[int]
) -> Dict[Tuple[int, int], float]:
    out: Dict[Tuple[int, int], float] = {}
    for source in sources:
        out.update(expected_bfs(adj, source))
    return out


def expected_mssp_weighted(
    adj: Sequence[Sequence[Tuple[int, float]]], sources: Sequence[int]
) -> Dict[Tuple[int, int], float]:
    out: Dict[Tuple[int, int], float] = {}
    for source in sources:
        out.update(expected_sssp(adj, source))
    return out


def expected_apsp_unweighted(adj: Sequence[Sequence[Tuple[int, float]]]) -> Dict[Tuple[int, int], float]:
    out: Dict[Tuple[int, int], float] = {}
    for source in range(len(adj)):
        if adj[source]:
            out.update(expected_bfs(adj, source))
    return out


def expected_apsp_weighted(adj: Sequence[Sequence[Tuple[int, float]]]) -> Dict[Tuple[int, int], float]:
    out: Dict[Tuple[int, int], float] = {}
    for source in range(len(adj)):
        if adj[source]:
            out.update(expected_sssp(adj, source))
    return out


def assert_maps_close(actual: Dict[Tuple[int, int], float], expected: Dict[Tuple[int, int], float], tol: float) -> None:
    if set(actual) != set(expected):
        missing = sorted(set(expected) - set(actual))
        extra = sorted(set(actual) - set(expected))
        raise AssertionError(f"key mismatch missing={missing[:8]} extra={extra[:8]}")
    for key, exp in expected.items():
        got = actual[key]
        if abs(got - exp) > tol:
            raise AssertionError(f"value mismatch for {key}: got {got}, expected {exp}")


def run_dawn(dawn: Path, args: Sequence[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [str(dawn), *args],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def make_cases() -> List[Tuple[str, int, bool, bool, List[Edge], List[int]]]:
    rng = random.Random(20240513)
    cases: List[Tuple[str, int, bool, bool, List[Edge], List[int]]] = []

    def weighted(u: int, v: int) -> float:
        return float(((u * 17 + v * 31) % 9) + 1)

    def random_undirected(n: int, probability: float) -> List[Edge]:
        out = [(i, i + 1, 1.0) for i in range(n - 1)]
        for u in range(n):
            for v in range(u + 2, n):
                if rng.random() < probability:
                    out.append((u, v, 1.0))
        return out

    def weighted_undirected(n: int, probability: float) -> List[Edge]:
        out = [(i, i + 1, weighted(i, i + 1)) for i in range(n - 1)]
        for u in range(n):
            for v in range(u + 2, n):
                if rng.random() < probability:
                    out.append((u, v, weighted(u, v)))
        return out

    def weighted_directed(n: int, probability: float) -> List[Edge]:
        out = [(i, i + 1, weighted(i, i + 1)) for i in range(n - 1)]
        for u in range(n):
            limit = min(n, u + 32)
            for v in range(u + 2, limit):
                if rng.random() < probability:
                    out.append((u, v, weighted(u, v)))
        return out

    def powerlaw_like(n: int, fanout: int) -> List[Edge]:
        out = [(0, 1, 1.0)]
        repeated = [0, 1]
        for v in range(2, n):
            targets = set()
            while len(targets) < min(fanout, v):
                targets.add(repeated[rng.randrange(len(repeated))])
            for u in targets:
                out.append((u, v, 1.0))
            repeated.extend(targets)
            repeated.extend([v] * fanout)
        return out

    cases.append(
        (
            "undirected_path_unweighted",
            128,
            False,
            False,
            canonical_edges([(i, i + 1, 1.0) for i in range(127)], False),
            [0, 64, 126],
        )
    )
    directed_chain = [(i, i + 1, 1.0) for i in range(159)]
    directed_chain += [(i, i + 5, 1.0) for i in range(0, 155, 5)]
    directed_chain += [(i, i + 17, 1.0) for i in range(0, 143, 17)]
    cases.append(
        (
            "directed_chain_unweighted",
            160,
            True,
            False,
            canonical_edges(directed_chain, True),
            [0, 17, 80],
        )
    )
    cases.append(
        (
            "random_undirected_unweighted",
            256,
            False,
            False,
            canonical_edges(random_undirected(256, 0.018), False),
            [0, 85, 255],
        )
    )
    cases.append(
        (
            "powerlaw_undirected_unweighted",
            512,
            False,
            False,
            canonical_edges(powerlaw_like(512, 3), False),
            [0, 128, 511],
        )
    )
    cases.append(
        (
            "undirected_weighted",
            300,
            False,
            True,
            canonical_edges(weighted_undirected(300, 0.012), False),
            [0, 75, 299],
        )
    )
    cases.append(
        (
            "directed_weighted",
            384,
            True,
            True,
            canonical_edges(weighted_directed(384, 0.11), True),
            [0, 96, 191],
        )
    )

    grid_edges = []
    width = 30
    height = 30
    for r in range(height):
        for c in range(width):
            node = r * width + c
            if c + 1 < width:
                grid_edges.append((node, node + 1, 1.0))
            if r + 1 < height:
                grid_edges.append((node, node + width, 1.0))
    cases.append(
        (
            "grid_undirected_unweighted",
            width * height,
            False,
            False,
            canonical_edges(grid_edges, False),
            [0, 450, 899],
        )
    )
    return cases


def check_case_algorithms(
    dawn: Path, workdir: Path, case: Tuple[str, int, bool, bool, List[Edge], List[int]]
) -> List[Tuple[str, str]]:
    name, n, directed, weighted, edges, sources = case
    case_dir = workdir / name
    case_dir.mkdir(parents=True, exist_ok=True)
    graph_path = case_dir / f"{name}.mtx"
    source_path = case_dir / "sources.txt"
    write_mtx(graph_path, n, edges, directed, weighted)
    write_sources(source_path, sources)
    adj = adjacency(n, edges, directed)
    failures: List[Tuple[str, str]] = []

    def record(algorithm: str, fn) -> None:
        try:
            fn()
            print(f"PASS {name}:{algorithm}")
        except SkipAlgorithm as exc:
            print(f"SKIP {name}:{algorithm}: {exc}")
        except Exception as exc:  # noqa: BLE001 - test harness should report all algorithms
            failures.append((algorithm, str(exc)))
            print(f"FAIL {name}:{algorithm}: {exc}")

    def check_bfs() -> None:
        if weighted:
            raise SkipAlgorithm("BFS is unweighted")
        out = case_dir / "bfs.out"
        run_dawn(
            dawn,
            [
                "run",
                "--algorithm",
                "bfs",
                "--input",
                str(graph_path),
                "--source",
                str(sources[0]),
                "--output",
                str(out),
            ],
        )
        assert_maps_close(parse_pairs(out, "int"), expected_bfs(adj, sources[0]), 0.0)

    def check_sssp() -> None:
        if not weighted:
            raise SkipAlgorithm("SSSP requires weighted graph")
        out = case_dir / "sssp.out"
        run_dawn(
            dawn,
            [
                "run",
                "--algorithm",
                "sssp",
                "--input",
                str(graph_path),
                "--source",
                str(sources[0]),
                "--output",
                str(out),
            ],
        )
        assert_maps_close(parse_pairs(out, "float"), expected_sssp(adj, sources[0]), 1e-4)

    def check_mssp() -> None:
        if not sources:
            return
        run_dawn(
            dawn,
            [
                "run",
                "--algorithm",
                "mssp",
                "--input",
                str(graph_path),
                "--source-list",
                str(source_path),
            ],
        )
        for source in sources:
            out = case_dir / f"mssp_{source}.out"
            run_dawn(
                dawn,
                [
                    "run",
                    "--algorithm",
                    "mssp",
                    "--input",
                    str(graph_path),
                    "--source-list",
                    str(source_path),
                    "--output-source",
                    str(source),
                    "--output",
                    str(out),
                ],
            )
            expected = expected_sssp(adj, source) if weighted else expected_bfs(adj, source)
            assert_maps_close(parse_pairs(out, "float" if weighted else "int"), expected, 1e-4 if weighted else 0.0)

    def check_apsp() -> None:
        run_dawn(dawn, ["run", "--algorithm", "apsp", "--input", str(graph_path)])
        for source in sources:
            if not adj[source]:
                continue
            out = case_dir / f"apsp_{source}.out"
            run_dawn(
                dawn,
                [
                    "run",
                    "--algorithm",
                    "apsp",
                    "--input",
                    str(graph_path),
                    "--output-source",
                    str(source),
                    "--output",
                    str(out),
                ],
            )
            expected = expected_sssp(adj, source) if weighted else expected_bfs(adj, source)
            assert_maps_close(parse_pairs(out, "float" if weighted else "int"), expected, 1e-4 if weighted else 0.0)

    def check_cc() -> None:
        cc_proc = run_dawn(
            dawn,
            [
                "run",
                "--algorithm",
                "cc",
                "--input",
                str(graph_path),
                "--source",
                str(sources[0]),
            ],
        )
        expected_cc = closeness_from_distances(
            dijkstra(adj, sources[0]) if weighted else bfs_distances(adj, sources[0]), n
        )
        for line in cc_proc.stdout.splitlines():
            if line.startswith("value:"):
                got = float(line.split(":", 1)[1].strip())
                if abs(got - expected_cc) > 1e-4:
                    raise AssertionError(f"got={got} expected={expected_cc}")
                return
        raise AssertionError("cc output missing value")

    def check_bc() -> None:
        if weighted:
            raise SkipAlgorithm("BC CPU kernel is unweighted")
        out = case_dir / "bc.out"
        run_dawn(
            dawn,
            ["run", "--algorithm", "bc", "--input", str(graph_path), "--output", str(out)],
        )
        expected_bc = {
            (-1, i): v
            for i, v in enumerate(brandes_unweighted(adj, directed))
            if abs(v) > 1e-7
        }
        assert_maps_close(parse_pairs(out, "float"), expected_bc, 1e-4)

    record("bfs", check_bfs)
    record("sssp", check_sssp)
    record("mssp", check_mssp)
    record("apsp", check_apsp)
    record("cc", check_cc)
    record("bc", check_bc)
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dawn", required=True, type=Path)
    parser.add_argument("--workdir", required=True, type=Path)
    parser.add_argument(
        "--strict",
        action="store_true",
        help="return non-zero when correctness mismatches are found",
    )
    args = parser.parse_args()

    if not args.dawn.exists():
        raise SystemExit(f"dawn executable not found: {args.dawn}")
    if args.workdir.exists():
        shutil.rmtree(args.workdir)
    args.workdir.mkdir(parents=True)

    failures: List[str] = []
    for case in make_cases():
        case_failures = check_case_algorithms(args.dawn, args.workdir, case)
        for algorithm, message in case_failures:
            failures.append(f"{case[0]}:{algorithm}: {message}")

    if failures:
        print("\nCorrectness failures:")
        for failure in failures:
            print(f"  {failure}")
        if args.strict:
            return 1
        print("Known correctness mismatches were recorded; rerun with --strict to fail.")
        return 0
    print("PASS all DAWN correctness cases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
